"""empty message

Revision ID: 16116987e465
Revises: 
Create Date: 2019-04-17 09:37:54.085142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16116987e465'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=250), nullable=False),
    sa.Column('formatted_text', sa.String(length=200), nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('service_identifier', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
