"""empty message

Revision ID: 7a23acd8479d
Revises: 841a04d6e6dd
Create Date: 2019-06-03 16:49:24.224674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a23acd8479d'
down_revision = '841a04d6e6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=100), nullable=True),
    sa.Column('service', sa.VARCHAR(length=20), nullable=True),
    sa.Column('service_identifier', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
