"""empty message

Revision ID: 841a04d6e6dd
Revises: 12cc9887678e
Create Date: 2019-06-03 16:17:59.985633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841a04d6e6dd'
down_revision = '12cc9887678e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('matched_term', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term')
    # ### end Alembic commands ###
